### ISSUE TITLE
Initializing the database takes a long time and is visually distracting.

### ISSUE THREAD

**Issue by leb-kuchen** [wiiznokes/cosmic-clipboard-manager#3]
Layout shifts are particular annoying, especially  if the dock is not extended.
[src/app.rs:73:9] start.elapsed() = 40.576382ms

**Comment by wiiznokes** [comment]
> Layout shifts are particular annoying, especially if the dock is not extended.

What do you mean by that ?

> [src/app.rs:73:9]

I do not see any code in this line.
If you're reffering of the latence when you open the applet, it's because of the initialisation of WGPU/tini-skia

**Comment by wiiznokes** [comment]
The database is only initialised at startup, and i don't think its a bootleneck

**Comment by leb-kuchen** [comment]
It's  the time, the applet takes to initialize, so you see `Clipboard` in the panel. I  created a `dbg!` for the db.  Sometimes the db takes way longer. I do not know, if it less annoying, it is in an icon, but there  are configurations where it is annoying.  You should consider making it an Option and return a Messages at startup, so definitely not high priority.

**Comment by leb-kuchen** [comment]
The problem is also, that the panel is dropped, every time you add or remove an applet.

**Comment by wiiznokes** [comment]
This is more a panel issue i think
