### ISSUE TITLE
Error on installation

### ISSUE THREAD

**Issue by Anikmoujegy** [wiiznokes/cosmic-clipboard-manager#33]
#### Bug Description:
got this error on installation
  

#### Logs, Panic Messages, Stack Traces:

cargo build -r
error: failed to parse manifest at `/home/anik/cosmic-clipboard-manager/Cargo.toml`

Caused by:
  no targets specified in the manifest
  either src/lib.rs, src/main.rs, a [lib] section, or [[bin]] section must be present
error: Recipe `install` failed on line 5 with exit code 101

**Comment by wiiznokes** [comment]
There is a `src/main.rs`. I suppose your environement isn't right. Maybe try to reclone the repo

**Comment by Anikmoujegy** [comment]
I've already tried that

**Comment by Anikmoujegy** [comment]
I will try again
