### ISSUE TITLE
Db is blocked and panics

### ISSUE THREAD

**Issue by leb-kuchen** [wiiznokes/cosmic-clipboard-manager#4]
Apr 03 05:44:28 pop-os /usr/libexec/gdm-wayland-session[3497]: 2024-04-03T03:44:28.322726Z  INFO cosmic-panel: cosmic_session::notifications: 2024-04-03T03:44:28.322652Z ERROR stderr{client=InnerClientId { ptr: 0x5f10f630da80, alive: false }}: com.wiiznokes.CosmicClipboardManager:    0: rust_begin_unwind
Apr 03 05:44:28 pop-os cosmic-session[3497]: 2024-04-03T03:44:28.319213Z ERROR stderr{client=InnerClientId { ptr: 0x5f10f630da80, alive: false }}: com.wiiznokes.CosmicClipboardManager: stack backtrace:
Apr 03 05:44:28 pop-os cosmic-session[3497]: 2024-04-03T03:44:28.319198Z ERROR stderr{client=InnerClientId { ptr: 0x5f10f630da80, alive: false }}: com.wiiznokes.CosmicClipboardManager: called `Result::unwrap()` on an `Err` value: Io(Custom { kind: Other, error: "could not acquire lock on \"/tmp/welcome-to-sled/db\": Os { code: 11, kind: WouldBlock, message: \"Resource temporarily unavailable\" }" })
Apr 03 05:44:28 pop-os cosmic-session[3497]: 2024-04-03T03:44:28.319164Z ERROR stderr{client=InnerClientId { ptr: 0x5f10f630da80, alive: false }}: com.wiiznokes.CosmicClipboardManager: thread 'main' panicked at src/app.rs:72:32:

**Comment by wiiznokes** [comment]
Did you try to run two instance of the app at the same time ?
